Configuration File:
  - configurationFiles/**

documentation:
  - docs/*.*

Kusto Query Language:
  - docs/KustoQueries/*

Log Analytics Language:
  - docs/LogAnalyticsQueries/*

Executable:
  - CollectSFData/**/*
  - CollectSFData.sln

WorkFlow:
  - .github/**
