root:
- changed-files:
  - any-glob-to-any-file: '*'

Configuration File:
- changed-files:
  - any-glob-to-any-file: configurationFiles/**

Executable:
- changed-files:
  - any-glob-to-any-file: src/**

Kusto Query Language:
- changed-files:
  - any-glob-to-any-file: kusto/**

WorkFlow:
- changed-files:
  - any-glob-to-any-file: .github/**

documentation:
- changed-files:
  - any-glob-to-any-file: 
    - docs/*.*
    - README.md
    - CHANGELOG.md

scripts:
- changed-files:
  - any-glob-to-any-file: scripts/*.*