# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

# windows-latest packages
# https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

name: ADO CI CollectSFData

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  project_name: CollectSFData
  project_root: .\src
  System.Debug: true

steps:
- task: PowerShell@2
  displayName: 'agent environment'
  inputs:
    targetType: 'inline'
    script: |
      [environment]::getenvironmentvariables().getenumerator()|sort Name
      dotnet --info
      dotnet nuget locals all --clear
    errorActionPreference: 'continue'
    verbosePreference: 'continue'
    debugPreference: 'continue'

- task: PowerShell@2
  displayName: 'dotnet restore'
  inputs:
    targetType: 'inline'
    script: |
      #write-host "dotnet restore `"$env:project_root\$env:project_name\$env:project_name.csproj`" -v detailed"
      #dotnet restore "$env:project_root\$env:project_name\$env:project_name.csproj" -v detailed
      nuget
      write-host "nuget update -self"
      nuget update -self
      nuget
      write-host "nuget restore `"$env:project_root\$env:project_name\$env:project_name.csproj`" -ConfigFile `"$env:project_root\nuget.config`""
      nuget restore "$env:project_root\$env:project_name\$env:project_name.csproj" -ConfigFile "$env:project_root\nuget.config"
    errorActionPreference: 'continue'
    verbosePreference: 'continue'
    debugPreference: 'continue'

# - task: NuGetRestore@1
#   displayName: 'NuGet restore'
#   inputs:
#     solution: '$(project_root)/$(project_name).sln'
#     selectOrConfig: 'config'

- task: PowerShell@2
  displayName: 'dotnet build'
  inputs:
    targetType: 'inline'
    script: |
      write-host "dotnet build `"$env:project_root\$env:project_name\$env:project_name.csproj`" -v detailed -c Release"
      dotnet build "$env:project_root\$env:project_name\$env:project_name.csproj" -v detailed -c Release
    errorActionPreference: 'continue'
    verbosePreference: 'continue'
    debugPreference: 'continue'

- task: PowerShell@2
  displayName: 'dotnet build output'
  inputs:
    targetType: 'inline'
    script: dir -recurse
    errorActionPreference: 'continue'
    verbosePreference: 'continue'
    debugPreference: 'continue'
