# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

name: collectsfdatabuild

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/CollectSFData.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Agent.BuildDirectory) # D:\a\1\s # Optional
    contents: '**\bin\**' 
    targetFolder: $(Build.ArtifactStagingDirectory) # d:\a\1\a
    cleanTargetFolder: true # Optional
    overWrite: true # Optional
    flattenFolders: false # Optional

- task: PublishBuildArtifacts@1