# used for internal ado builds

name: ADO CI CollectSFData

trigger:
  branches:
    include:
    - 'master'

pool:
  vmImage: 'windows-latest'

variables:
  project_name: CollectSFData
  project_root: .\src
  System.Debug: true
  buildConfiguration: Release
  Codeql.PublishDatabaseLog: true
  # testing
  Codeql.Cadence: 0
  Codeql.LogLevel: 5
  Codeql.Language: csharp,powershell
  Codeql.PublishDatabase: true

steps:
- task: PowerShell@2
  displayName: 'agent environment'
  inputs:
    targetType: 'inline'
    script: |
      [environment]::getenvironmentvariables().getenumerator()|sort Name
      dotnet --info
      dotnet nuget locals all --clear
    errorActionPreference: 'continue'
    verbosePreference: 'continue'
    debugPreference: 'continue'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(project_root)/$(project_name).sln'
    feedsToUse: 'config'
    nugetConfigPath: './nuget.config'
    noCache: false
    verbosityRestore: 'Detailed'

- task: CodeQL3000Init@0
  inputs:
    Enabled: true
    AnalyzeInPipeline: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build' # 'build' | 'push' | 'pack' | 'publish' | 'restore' | 'run' | 'test' | 'custom'. Required. Command. Default: build.
    projects: '**/$(project_name)/$(project_name).csproj'
    arguments: '-v detailed -c $(buildConfiguration)'
    packagesToPack: '**/*.csproj' # string. Alias: searchPatternPack. Required when command = pack. Path to csproj or nuspec file(s) to pack. Default: **/*.csproj.
    configuration: '$(buildConfiguration)' # string. Alias: configurationToPack. Optional. Use when command = pack. Configuration to Package. Default: $(BuildConfiguration).
    includesymbols: true # boolean. Optional. Use when command = pack. Include Symbols. Default: false.
    feedsToUse: 'config' # 'select' | 'config'. Alias: selectOrConfig. Required when command = restore. Feeds to use. Default: select.
    verbosityRestore: 'Detailed' # '-' | 'Quiet' | 'Minimal' | 'Normal' | 'Detailed' | 'Diagnostic'. Optional. Use when command = restore. Verbosity. Default: Detailed.
    verbosityPack: 'Detailed' # '-' | 'Quiet' | 'Minimal' | 'Normal' | 'Detailed' | 'Diagnostic'. Optional. Use when command = pack. Verbosity. Default: Detailed.

- task: ManifestGeneratorTask@0
  inputs:
    BuildDropPath: '.\src'
    ManifestDirPath: '.\src\bin'
    BuildComponentPath: '.\src'
    Verbosity: 'Verbose'
    PackageName: 'CollectSFData'

- task: CodeQL3000Finalize@0
  condition: always()
  continueOnError: true

- task: PowerShell@2
  displayName: 'dotnet build output'
  inputs:
    targetType: 'inline'
    script: dir -recurse
    errorActionPreference: 'continue'
    verbosePreference: 'continue'
    debugPreference: 'continue'

- task: CredScan@3
  inputs:
    verboseOutput: true

- task: AntiMalware@4
  inputs:
    InputType: 'Basic'
    ScanType: 'CustomScan'
    FileDirPath: '$(Build.StagingDirectory)'
    TreatSignatureUpdateFailureAs: 'Warning'
    SignatureFreshness: 'UpToDate'
    TreatStaleSignatureAs: 'Error'

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/src/bin/$(buildConfiguration)
    artifactName: $(project_name)-$(buildConfiguration)
