// 
//    This code was generated by EtwEventTypeGen.exe 
//

using System;
using Tx.Windows;

namespace CollectSFData.DataFile.Microsoft_ServiceFabric_DataImpl
{
    public enum EventTask : uint    {
        ManagedGeneral = 224,
        ManagementCommon = 225,
        ImageStoreClient = 226,
        FabricHost = 227,
        FabricDeployer = 228,
        SystemFabricDeployer = 229,
        Test = 230,
        AzureLogCollector = 231,
        SystemFabric = 232,
        ImageBuilder = 233,
        FabricDCA = 234,
        FabricHttpGateway = 235,
        InfrastructureService = 236,
        ManagedTokenValidationService = 237,
        DSTSClient = 238,
        TStore = 240,
        DistributedDictionary = 241,
        DistributedQueue = 242,
        Wave = 243,
        ReliableStream = 244,
        DistributedVersionedDictionary = 245,
        Testability = 246,
        RandomActionGenerator = 247,
        TReplicator = 249,
        TStatefulServiceReplica = 250,
        TStateManager = 251,
        ActorFramework = 252,
        WRP = 253,
        ServiceFramework = 254,
        FaultAnalysisService = 255,
        ApiMonitor = 256,
        ReliableConcurrentQueue = 257,
        UpgradeOrchestrationService = 258,
        BackupRestoreService = 259,
        BackupCopier = 260,
        ManagedHosting = 261,
        GatewayResourceManager = 262,
        ManagedIdentityTokenService = 263,
        Max = 264,
    }

    [Format("recovery completed. CheckpointLSN: %2.")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 64377, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStateManager_LocalStateRecoverCheckpointEnd : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:Int64")]
        public long checkpointLSN { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("LSN: %2 PSN: %3 RecordPosition: %4 HighestBackedupEpoch: <%5, %6> HighestBackedupLSN: %7")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 63898, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TReplicator_UndoBackupLogRecord : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:Int64")]
        public long lsn { get; set; }

        [EventField("win:Int64")]
        public long psn { get; set; }

        [EventField("win:UInt64")]
        public ulong recordPosition { get; set; }

        [EventField("win:Int64")]
        public long dataloss { get; set; }

        [EventField("win:Int64")]
        public long configuration { get; set; }

        [EventField("win:Int64")]
        public long highestBackedupLsn { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("Backup Deleted. LSN: %2 PSN: %3 Position: %4")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 62483, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TReplicator_TruncateTailBackup : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:Int64")]
        public long lsn { get; set; }

        [EventField("win:Int64")]
        public long psn { get; set; }

        [EventField("win:UInt64")]
        public ulong position { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("SPId: %2 Api: Function: %3.")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 64437, 2,
    "", "win:Error", "Microsoft-ServiceFabric-DataImpl/Admin", "DataMessaging")]

    public class Event_TStateManager_ISP2_ApiError : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:Int64")]
        public long stateProviderId { get; set; }

        [EventField("win:UnicodeString")]
        public string functionName { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("Starting full copy, ProgressVector validation failed.  Error Message: %2 SourceProgressVector: %3 SourceIndex: %4. SourceProgressVectorEntry: %5  TargetProgressVector: %6 TargetIndex: %7. TargetProgressVectorEntry: %8 ")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 63829, 2,
    "", "win:Warning", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TReplicator_ProgressVectorValidationTelemetry : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string errorMessage { get; set; }

        [EventField("win:UnicodeString")]
        public string sourceVector { get; set; }

        [EventField("win:Int64")]
        public long sourceIndex { get; set; }

        [EventField("win:UnicodeString")]
        public string sourceVectorEntry { get; set; }

        [EventField("win:UnicodeString")]
        public string targetVector { get; set; }

        [EventField("win:Int64")]
        public long targetIndex { get; set; }

        [EventField("win:UnicodeString")]
        public string targetVectorEntry { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("State: %2. Last Periodic Checkpoint : %3. Last Periodic Truncation : %4")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 63830, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TReplicator_PeriodicCheckpointTruncation : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string periodicCheckpointTruncationState { get; set; }

        [EventField("win:UnicodeString")]
        public string lastChkptTime { get; set; }

        [EventField("win:UnicodeString")]
        public string lastTruncationTime { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("Drain of %2 stream completed. Drain status: %3. Number of records: %4. Last record Type: %5 LSN: %6 PSN: %7 Position: %8")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 63812, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TReplicator_DrainCompleted : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string stream { get; set; }

        [EventField("win:UnicodeString")]
        public string status { get; set; }

        [EventField("win:Int64")]
        public long number { get; set; }

        [EventField("win:UInt32")]
        public uint recordType { get; set; }

        [EventField("win:Int64")]
        public long lsn { get; set; }

        [EventField("win:Int64")]
        public long psn { get; set; }

        [EventField("win:UInt64")]
        public ulong position { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("directory=%2 diskwrite=%3bytes/sec")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61549, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_ProcessCompleteCopyOperation : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string directory { get; set; }

        [EventField("win:Int64")]
        public long avgDiskWriteBytesPerSec { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("CheckpointFileWrite=%2bytes/sec")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61572, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_CheckpointFileWriteBytesPerSec : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:Int64")]
        public long fileWriteBytesPerSec { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("starting")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61591, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_SweepOnReads : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReplicaId: %2 StoreCount: %3")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61583, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_StoreCountTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int64")]
        public long numberOfStores { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReliableDictionaryCount: %2 ReliableQueueCount: %3 ReliableConcurrentQueueCount: %4 TStoreCount: %5")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 63850, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStateManager_StateProviderCountTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long numberOfRDs { get; set; }

        [EventField("win:Int64")]
        public long numberOfRQs { get; set; }

        [EventField("win:Int64")]
        public long numberOfRCQs { get; set; }

        [EventField("win:Int64")]
        public long numberOfTStores { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReliableDictionaryDiskSize: %2 ReliableQueueDiskSize: %3 ReliableConcurrentQueueDiskSize: %4 TStoreDiskSize: %5")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 63851, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStateManager_StateProviderDiskSizeTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long diskSizeRD { get; set; }

        [EventField("win:Int64")]
        public long diskSizeRQ { get; set; }

        [EventField("win:Int64")]
        public long diskSizeRCQs { get; set; }

        [EventField("win:Int64")]
        public long diskSizeTStore { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReplicaId: %2 NumReads: %3 NumWrites: %4")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61588, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_ReadWriteTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int64")]
        public long numberOfReads { get; set; }

        [EventField("win:Int64")]
        public long numberOfWrites { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReplicaId: %2 TotalReadLatency (us): %3 NumReads: %4 LastReadLatency (us): %5 LastReadOwner: %6 lastReadKeyLocation: %7 lastReadValueSize: %8 LastReadWaitedForLock: %9 LastReadTimedOut: %10 LastReadLoadedFromDisk: %11")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61589, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_ReadLatencyTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int64")]
        public long totalReadLatencyInUs { get; set; }

        [EventField("win:Int64")]
        public long numberOfReads { get; set; }

        [EventField("win:Int64")]
        public long lastReadLatencyInUs { get; set; }

        [EventField("win:UnicodeString")]
        public string lastReadOwner { get; set; }

        [EventField("win:UnicodeString")]
        public string lastReadKeyLocation { get; set; }

        [EventField("win:Int32")]
        public int lastReadValueSize { get; set; }

        [EventField("win:Boolean")]
        public bool lastReadWaitedForLock { get; set; }

        [EventField("win:Boolean")]
        public bool lastReadTimedOut { get; set; }

        [EventField("win:Boolean")]
        public bool lastReadLoadedFromDisk { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReplicaId: %2 LastReadLatency (us): %3 LastReadValueSize: %4 LastReadLoadedFromDisk: %5")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61596, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_EnumerationReadLatencyTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int64")]
        public long readLatencyInUs { get; set; }

        [EventField("win:Int32")]
        public int readValueSize { get; set; }

        [EventField("win:Boolean")]
        public bool readLoadedFromDisk { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReplicaId: %2 LastReadLatency (us): %3 LastReadValueSize: %4 LastReadLoadedFromDisk: %5 LastReadKeyLocation: %6")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61597, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_PointReadLatencyTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int64")]
        public long readLatencyInUs { get; set; }

        [EventField("win:Int32")]
        public int readValueSize { get; set; }

        [EventField("win:Boolean")]
        public bool readLoadedFromDisk { get; set; }

        [EventField("win:UnicodeString")]
        public string readKeyLocation { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReplicaId: %2 NumEnumerationReads: %3 NumPointReads: %4")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61598, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_EnumerationPointReadRatioTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int64")]
        public long numberOfEnumerationReads { get; set; }

        [EventField("win:Int64")]
        public long numberOfPointReads { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReplicaId: %2 NotificationEnabled: %3")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61582, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_StoreNotificationsTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int32")]
        public int notificationsEnabled { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReplicaId: %2 TotalKeySize: %3 NumKeys: %4 TotalValueSize: %5 NumValues: %6")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61586, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_KeyValueSizeTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int64")]
        public long totalKeySize { get; set; }

        [EventField("win:Int64")]
        public long numberOfKeys { get; set; }

        [EventField("win:Int64")]
        public long totalValueSize { get; set; }

        [EventField("win:Int64")]
        public long numberOfValues { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReplicaId: %2 PrimitiveKeyCount: %3")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61592, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_PrimitiveKeyTypeTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int32")]
        public int primitiveKeyCount { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReplicaId: %2 StringKeyCount: %3")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61593, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_StringKeyTypeTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int32")]
        public int stringKeyCount { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReplicaId: %2 GuidKeyCount: %3")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61594, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_GuidKeyTypeTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int32")]
        public int guidKeyCount { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReplicaId: %2 OtherKeyCount: %3")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61595, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_OtherKeyTypeTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int32")]
        public int otherKeyCount { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReplicaId: %2 TotalItemCount: %3")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61584, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_ItemCountTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int64")]
        public long totalItemCount { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReplicaId: %2 TotalDiskSize: %3")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61585, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_DiskSizeTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int64")]
        public long totalDiskSize { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("Merged filename=%2, FileId=%3, TotalCount=%4, ActiveCount=%5, DeletedKeyCount=%6, CheckpointFileWrite=%7bytes/sec")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61566, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_MergeFile : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string filename { get; set; }

        [EventField("win:Int64")]
        public long fileId { get; set; }

        [EventField("win:Int64")]
        public long totalCount { get; set; }

        [EventField("win:Int64")]
        public long activeCount { get; set; }

        [EventField("win:Int64")]
        public long deletedKeyCount { get; set; }

        [EventField("win:Int64")]
        public long fileWriteBytesPerSec { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("%2: Filename=%3, FileId=%4, TotalCount=%5, DeletedKeyCount=%6, InvalidKeyCount=%7")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61570, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_CheckpointFileMetadata : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string phase { get; set; }

        [EventField("win:UnicodeString")]
        public string filename { get; set; }

        [EventField("win:Int64")]
        public long fileId { get; set; }

        [EventField("win:Int64")]
        public long totalCount { get; set; }

        [EventField("win:Int64")]
        public long deletedKeyCount { get; set; }

        [EventField("win:Int64")]
        public long invalidKeyCount { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("Copy aborted")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61590, 2,
    "", "win:Warning", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_EndSettingCurrentStateCopyAborted : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ItemCount=%2 DiskSize=%3")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61573, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_StoreSize : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:Int64")]
        public long itemCount { get; set; }

        [EventField("win:Int64")]
        public long diskSize { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("MergePolicy=%2")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61571, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_MergePolicy : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string mergePolicy { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("Last FileId: %2 Duration: %3 ms ItemCount: %4 DiskSize: %5")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61692, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_PerformCheckpointAsyncCompleted : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UInt32")]
        public uint fileId { get; set; }

        [EventField("win:Double")]
        public double durationInMs { get; set; }

        [EventField("win:Int64")]
        public long itemCount { get; set; }

        [EventField("win:Int64")]
        public long diskSize { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("%2")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 64438, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStateManager_BackgroundSweepTask : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string message { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("%2")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 64439, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStateManager_SweepManagerInfo : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string message { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("%2")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 64440, 2,
    "", "win:Warning", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStateManager_SweepManagerWarning : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string message { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("Id: %2 TotalCommitLatency (us): %3 NumCommits: %4 NumSingleOpCommits: %5 NumFaultedCommits: %6 LastCommitLatency (us): %7")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 63833, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TReplicator_CommitLatencyTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int64")]
        public long totalCommitLatencyInUs { get; set; }

        [EventField("win:Int64")]
        public long numberOfCommits { get; set; }

        [EventField("win:Int64")]
        public long numberOfSingleOperationCommits { get; set; }

        [EventField("win:Int64")]
        public long numberOfFaultedCommits { get; set; }

        [EventField("win:Int64")]
        public long lastCommitLatencyInUs { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("ReplicaId: %2 RCViewer GetCollectionsCalls: %3 GetItemCalls: %4 GetItemsCalls: %5")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 63840, 2,
    "", "win:Warning", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStateManager_RCViewerServiceCallCountTelemetry : SystemEvent
    {
        [EventField("win:GUID")]
        public Guid id { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int64")]
        public long getCollectionsCalls { get; set; }

        [EventField("win:Int64")]
        public long getItemCalls { get; set; }

        [EventField("win:Int64")]
        public long getItemsCalls { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("%2")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61469, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_VolatileCopyStreamInfo : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string msg { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("%2")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61456, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_VolatileCopyManagerInfo : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string msg { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("%2")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61462, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_VolatileCopyManagerWarning : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string msg { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("KeysInChunk=%2 RunningKeyCount=%3 KeyBytes=%4 ValueBytes=%5")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61463, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_VolatileCopyManagerProcessDataCopyOperation : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:Int64")]
        public long keysInChunk { get; set; }

        [EventField("win:Int64")]
        public long runningTotal { get; set; }

        [EventField("win:Int32")]
        public int keyBytes { get; set; }

        [EventField("win:Int32")]
        public int valueBytes { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("KeysInChunk=%2 RunningKeyCount=%3 KeyBytes=%4 ValueBytes=%5")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61510, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Debug", "Default")]

    public class Event_TStore_VolatileCopyStreamOnCopyStageData : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:Int64")]
        public long keysInChunk { get; set; }

        [EventField("win:Int64")]
        public long runningTotal { get; set; }

        [EventField("win:Int32")]
        public int keyBytes { get; set; }

        [EventField("win:Int32")]
        public int valueBytes { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, Id: %4@%5@%6@%7")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61701, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_DistributedDictionary__ReplicasOps_ReliableDictionaryOpenedEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string stateProviderName { get; set; }

        [EventField("win:Int64")]
        public long stateProviderId { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, Id: %4@%5@%6@%7")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61702, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_DistributedDictionary__ReplicasOps_ReliableDictionaryClosedEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string stateProviderName { get; set; }

        [EventField("win:Int64")]
        public long stateProviderId { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, Id: %4@%5@%6@%7, RecoveredCount: %8, CheckpointLSN: %9, TimeTaken: %10ms")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61703, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_DistributedDictionary__ReplicasOps_ReliableDictionaryCheckpointRecoveredEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string stateProviderName { get; set; }

        [EventField("win:Int64")]
        public long stateProviderId { get; set; }

        [EventField("win:Int64")]
        public long recoveredCount { get; set; }

        [EventField("win:Int64")]
        public long checkpointLsn { get; set; }

        [EventField("win:Int64")]
        public long elapsedMilliseconds { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, Id: %4@%5@%6@%7, BytesSent: %8, TimeTaken: %9ms, DiskReadRate: %10bytes/sec")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61704, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_DistributedDictionary__ReplicasOps_ReliableDictionaryCheckpointFilesSentEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string stateProviderName { get; set; }

        [EventField("win:Int64")]
        public long stateProviderId { get; set; }

        [EventField("win:Int64")]
        public long bytesSent { get; set; }

        [EventField("win:Int64")]
        public long elapsedMilliseconds { get; set; }

        [EventField("win:Int64")]
        public long diskReadRate { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, Id: %4@%5@%6@%7, BytesReceived: %8, TimeTaken: %9ms, DiskWriteRate: %10bytes/sec")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61705, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_DistributedDictionary__ReplicasOps_ReliableDictionaryCheckpointFilesReceivedEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string stateProviderName { get; set; }

        [EventField("win:Int64")]
        public long stateProviderId { get; set; }

        [EventField("win:Int64")]
        public long bytesReceived { get; set; }

        [EventField("win:Int64")]
        public long elapsedMilliseconds { get; set; }

        [EventField("win:Int64")]
        public long diskWriteRate { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, Id: %4@%5@%6@%7")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61963, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_DistributedQueue__ReplicasOps_ReliableQueueOpenedEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string stateProviderName { get; set; }

        [EventField("win:Int64")]
        public long stateProviderId { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, Id: %4@%5@%6@%7")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61964, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_DistributedQueue__ReplicasOps_ReliableQueueClosedEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string stateProviderName { get; set; }

        [EventField("win:Int64")]
        public long stateProviderId { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, Id: %4@%5@%6@%7, RecoveredCount: %8, CheckpointLSN: %9, TimeTaken: %10ms")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61965, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_DistributedQueue__ReplicasOps_ReliableQueueCheckpointRecoveredEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string stateProviderName { get; set; }

        [EventField("win:Int64")]
        public long stateProviderId { get; set; }

        [EventField("win:Int64")]
        public long recoveredCount { get; set; }

        [EventField("win:Int64")]
        public long checkpointLsn { get; set; }

        [EventField("win:Int64")]
        public long elapsedMilliseconds { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, Id: %4@%5@%6@%7, BytesSent: %8, TimeTaken: %9ms, DiskReadRate: %10bytes/sec")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61966, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_DistributedQueue__ReplicasOps_ReliableQueueCheckpointFilesSentEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string stateProviderName { get; set; }

        [EventField("win:Int64")]
        public long stateProviderId { get; set; }

        [EventField("win:Int64")]
        public long bytesSent { get; set; }

        [EventField("win:Int64")]
        public long elapsedMilliseconds { get; set; }

        [EventField("win:Int64")]
        public long diskReadRate { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, Id: %4@%5@%6@%7, BytesReceived: %8, TimeTaken: %9ms, DiskWriteRate: %10bytes/sec")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61967, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_DistributedQueue__ReplicasOps_ReliableQueueCheckpointFilesReceivedEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string stateProviderName { get; set; }

        [EventField("win:Int64")]
        public long stateProviderId { get; set; }

        [EventField("win:Int64")]
        public long bytesReceived { get; set; }

        [EventField("win:Int64")]
        public long elapsedMilliseconds { get; set; }

        [EventField("win:Int64")]
        public long diskWriteRate { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, Id: %4@%5@%6@%7")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 63647, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_ReliableConcurrentQueue__ReplicasOps_ReliableConcurrentQueueOpenedEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string stateProviderName { get; set; }

        [EventField("win:Int64")]
        public long stateProviderId { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, Id: %4@%5@%6@%7")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 63648, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_ReliableConcurrentQueue__ReplicasOps_ReliableConcurrentQueueClosedEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string stateProviderName { get; set; }

        [EventField("win:Int64")]
        public long stateProviderId { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, Id: %4@%5@%6@%7, RecoveredCount: %8, TimeTaken: %9ms")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 63649, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_ReliableConcurrentQueue__ReplicasOps_ReliableConcurrentQueueCheckpointRecoveredEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string stateProviderName { get; set; }

        [EventField("win:Int64")]
        public long stateProviderId { get; set; }

        [EventField("win:Int64")]
        public long recoveredCount { get; set; }

        [EventField("win:Int64")]
        public long elapsedMilliseconds { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, EventInstanceId: %3, Id: %6, ErrorMsg: %7, StackTrace: %8")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61687, 2,
    "", "win:Error", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_TStore__ReplicasOps_TStoreErrorEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string id { get; set; }

        [EventField("win:UnicodeString")]
        public string message { get; set; }

        [EventField("win:UnicodeString")]
        public string stackTrace { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, Id: %4.%5, TargetReplicaId: %6, Reason: %7, StartingLogRecordPosition: %8, EndingLogRecordPosition: %9")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 63831, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_TReplicator__ReplicasOps_PrimaryFullCopyInitiatedEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int64")]
        public long targetReplicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string reason { get; set; }

        [EventField("win:UInt64")]
        public ulong startingLogRecordPosition { get; set; }

        [EventField("win:UInt64")]
        public ulong endingLogRecordPosition { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, Id: %4.%5, TargetReplicaId: %6, StartingLogRecordPosition: %7, EndingLogRecordPosition: %8")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 63832, 2,
    "", "win:Informational", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_TReplicator__ReplicasOps_PrimaryPartialCopyInitiatedEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:Int64")]
        public long targetReplicaId { get; set; }

        [EventField("win:UInt64")]
        public ulong startingLogRecordPosition { get; set; }

        [EventField("win:UInt64")]
        public ulong endingLogRecordPosition { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

    [Format("EventName: %1, Category: %2, EventInstanceId: %3, PartitionId: %4, ReplicaId: %5, ErrorMsg: %6, ProcessId: %8, StackTrace: %7")]

    [ManifestEvent("{02d06793-efeb-48c8-8f7f-09713309a810}", 61685, 2,
    "", "win:Error", "Microsoft-ServiceFabric-DataImpl/Operational", "Default")]

    public class Event_TReplicator__ReplicasOps_TReplicatorErrorEvent : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string eventName { get; set; }

        [EventField("win:UnicodeString")]
        public string category { get; set; }

        [EventField("win:GUID")]
        public Guid eventInstanceId { get; set; }

        [EventField("win:GUID")]
        public Guid partitionId { get; set; }

        [EventField("win:Int64")]
        public long replicaId { get; set; }

        [EventField("win:UnicodeString")]
        public string message { get; set; }

        [EventField("win:UnicodeString")]
        public string stackTrace { get; set; }

        [EventField("win:Int32")]
        public int processId { get; set; }

        [EventField("win:UnicodeString")]
        public string EventType { get; set; }
    }

}
